service: crud-api-serverless

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: todo-List-ServerlessUser
  environment:
    myDynamoDBTable: ${self:custom.myDynamoDBTable}
    JWT_SECRET: ${self:custom.secret.jwtSecret}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

custom:
  myDynamoDBTable: todoLists
  secret: ${file(secret.json)}

functions:
  createNote:
    handler: src/lambdas/createNote.handler
    events:
      - http:
          path: todoLists/create-note
          method: POST
          cors: true
          request:
            schemas:
              application/json: ${file(src/schema/todoLists.json)}

  getAllNotes:
    handler: src/lambdas/getAllNotes.handler
    events:
      - http:
          path: todoLists/get-notes
          method: GET
          cors: true

  deleteNote:
    handler: src/lambdas/deleteNote.handler
    events:
      - http:
          path: todoLists/delete-note/{id_Note}
          method: DELETE
          cors: true

  updateNote:
    handler: src/lambdas/updateNote.handler
    events:
      - http:
          path: todoLists/update-note/{id_Note}
          method: PATCH
          cors: true
          request:
            schemas:
              application/json: ${file(src/schema/todoLists.json)}

resources:
  Resources:
    myDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.myDynamoDBTable}
        AttributeDefinitions:
          - AttributeName: id_Note
            AttributeType: S
        KeySchema:
          - AttributeName: id_Note
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
